spring:
  application:
    name: paiagent-api
  datasource:
    url: jdbc:h2:file:./data/paiagent-db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
